#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# aliases
alias ls='ls --color=auto'
alias g='git'

PS1='[\u@\h \W]\$ '

if [ -f /etc/bash_completion ]; then

	. /etc/bash_completion

fi

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

