set nocompatible " be iMproved
filetype off     " required

" Setup Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/vundle.vim'

" tpope utilities
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-speeddating'

" Workflow
Plugin 'Townk/vim-autoclose'
Plugin 'ervandew/supertab'
Plugin 'godlygeek/tabular'
Plugin 'jeetsukumaran/vim-buffergator'
Plugin 'justinmk/vim-sneak'
Plugin 'kien/ctrlp.vim'
Plugin 'msanders/snipmate.vim'
Plugin 'rking/ag.vim'
Plugin 'vim-scripts/IndexedSearch'
Plugin 'terryma/vim-expand-region'
Plugin 'bling/vim-airline'
Plugin 'vimwiki/vimwiki'

" Colors
Plugin 'flazz/vim-colorschemes'

" Objective C
Plugin 'dvor/cocoa.vim'
Plugin 'tokorom/xcode-actions.vim'
Plugin 'brow/vim-xctool'

" Swift
Plugin 'toyamarinyon/vim-swift'

call vundle#end()         " required
filetype plugin indent on " required


source $HOME/.vim/config.vim
source $HOME/.vim/colors.vim
source $HOME/.vim/plugins.vim
source $HOME/.vim/shortcuts.vim
source $HOME/.vim/autocommands.vim

