set nocompatible " be iMproved

" Setup Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#rc()
Plugin 'gmarik/vundle.vim'

" tpope utilities
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-speeddating'

" Workflow
Plugin 'Townk/vim-autoclose'
Plugin 'ervandew/supertab'
Plugin 'godlygeek/tabular'
Plugin 'jeetsukumaran/vim-buffergator'
Plugin 'justinmk/vim-sneak'
Plugin 'kien/ctrlp.vim'
Plugin 'msanders/snipmate.vim'
Plugin 'rking/ag.vim'
" Plugin 'scrooloose/syntastic'
Plugin 'vim-scripts/IndexedSearch'

" Colors
Plugin 'bling/vim-airline'
Plugin 'flazz/vim-colorschemes'

" Objective C
Plugin 'Rip-Rip/clang_complete'
Plugin 'dvor/cocoa.vim'


"Plugin 'mileszs/ack.vim'
"Plugin 'scrooloose/nerdcommenter'
"Plugin 'Lokaltog/vim-powerline'
"Plugin 'Lokaltog/vim-easymotion'
"Plugin 'terryma/vim-multiple-cursors'


source $HOME/.vim/config.vim
source $HOME/.vim/colors.vim
source $HOME/.vim/plugins.vim
source $HOME/.vim/shortcuts.vim
source $HOME/.vim/autocommands.vim

